version: '3.8'

services:
  aws:
    image: amazon/aws-cli:latest
    container_name: aws-cli
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=ap-northeast-1
