name: Dev Deploy

on:
  push:
    branches:
      - master
    paths: 
      - 'src/dev/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo development

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
