# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION=ap-northeast-1
      
      - name: Create revision with CodeDeploy
        run: |
          aws deploy push \
          --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
          --description "This is a revision for the ${{ secrets.CODEDEPLOY_APP_NAME }}-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://${{ secrets.S3_ARTIFACT_BUCKET }}/${{ secrets.CODEDEPLOY_APP_NAME }}-${{ github.sha }}.zip \
          --source .

      - name: Create Deployment with CodeDeploy
        run: |
          aws deploy create-deployment \
           --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
           --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }} \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=${{ secrets.S3_ARTIFACT_BUCKET }},key=${{ secrets.CODEDEPLOY_APP_NAME }}-${{ github.sha }}.zip,bundleType=zip \
